// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmhkqecxstimuzslviab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaGtxZWN4c3RpbXV6c2x2aWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzMxMzIsImV4cCI6MjA3NDMwOTEzMn0.rgedj2x6ctL2R0WSu2Qdes6vvrsXDK01rt-ywy9mWmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});